import zmq

game_descriptions = {
    "Arena Gods":"ARENA GODS is Spectacle Combat, a top-down, arena fighting game where two to four gladiators compete to be the last one standing in an anything goes deathmatch spectacle. You are gladiator. Brave the arena and win the crowd to seize godhood!",
    "Astro Duel":"Astro Duel is a competitive local multiplayer party game. Rounds are quick and death is sudden. Blast your friends into space. Run over their helpless bodies for good measure.",
    "Battleblock Theater":"Shipwrecked. Captured. Betrayed. Forced to perform for an audience of cats? Yes, all that and more when you unlock BattleBlock Theater! There's no turning back once you've started on your quest to free over 300 of your imprisoned friends from evil technological cats. Immerse yourself in this mind bending tale of treachery as you use your arsenal of weapon-tools to battle your way through hundreds of levels in order to discover the puzzling truth behind BattleBlock Theater.",
    "Blaze Rush":"BlazeRush is a dynamic arcade racing survival game with no health, no levelling and no brakes! You can assemble a team of friends to play in local or online multiplayer, choose a car to your taste and chase, blow up and cut off! Adapt your style and tactics to new enemies, obstacles and tracks.",
    "Broforce":"When evil threatens the world, the world calls on Broforce - an under-funded, over-powered paramilitary organization dealing exclusively in excessive force. Brace your loins with up to four players to run 'n' gun as dozens of different bros and eliminate the opposing terrorist forces that threaten our way of life. Unleash scores of unique weapons and set off incredible chain reactions of fire, napalm, and limbs in the name of freedom.", 
    "Brotato":"A spaceship from Potato World crashes onto an alien planet. The sole survivor: Brotato, the only potato capable of handling 6 weapons at the same time. Waiting to be rescued by his mates, Brotato must survive in this hostile environment.",
    "Chaotic Voic":"Chaotic Void is a wacky local couch brawler game set in zero gravity space with unique physics gameplay, a multitude of crazy weapons, coldly inhospitable environments, and feisty space-themed characters. It's brutal. It's fun. It's chaotic!", 
    "ChargeShot":"Annually, from across dozens of galactic sectors, men, girblons, women, and children tune in to their local space TV stations for the most anticipated event of the year: “ChargeShot”. Bounty hunters from across the known universe compete annually for eternal glory and a coveted $2,000,001 space-credit reward. In ChargeShot, each player is armed with a Pulsar Cannon, capable of powerful blasts that bounce off walls and instantly destroy any life forms they touch; an Energy Shield, which can reflect Pulsar blasts and knock opponents into dangerous hazards; and a standard-issue jetpack for traversing the battlefield with deadly speed and grace. Test your reflexes against up to 3 other friends (or enemies, as the case may be by the end of the night).", 
    "Crawl":"Crawl is the dungeon crawler where your friends control the monsters! Battle through randomly generated dungeons full of cruel traps and horrid beasts- all controlled by the other players. If a friend kills you they take your place and it's their turn to crawl! It's a race to gain enough XP and loot to face them all as they control the flailing limbs of the hulking final boss!", 
    "Cuphead":"Cuphead is a classic run and gun action game heavily focused on boss battles. Inspired by cartoons of the 1930s, the visuals and audio are painstakingly created with the same techniques of the era, i.e. traditional hand drawn cel animation, watercolor backgrounds, and original jazz recordings. Play as Cuphead or Mugman (in single player or local co-op) as you traverse strange worlds, acquire new weapons, learn powerful super moves, and discover hidden secrets while you try to pay your debt back to the devil!",
    "Dirty Dirty Pirates":"You're a dirty scallywag with nothing to lose. Dirty Dirty Pirates is a fast-paced, chaotic, player versus player fighting game, where fast reflexes and improvisation will help you become victorious. Stab, throw, roll, dance, mount, catch, and smash your way through frenzied battles in a looped battleground and enjoy the hilarious brutality.",
    "Duck Game":"Enter the futuristic year of 1984, an age where ducks run wild in a frantic battle for glory. Win over the crowd and gain a following by blasting your feathered friends with Shotguns, Net Guns, Mind Control Rays, Saxophones, Magnet Guns, and pretty much anything else a duck could use as a weapon. One hit and you're roasted. This is DUCK GAME. Don't blink.",
    "Flat Heroes":"When was the last time you felt like a hero? Flat Heroes rewards you with that good old feeling of surviving impossible levels alongside a smooth modern design with a minimalist style. With a simple set of movements — Run. Jump. Dash. Attack. — and delightful controls, Flat Heroes encourages you to stylishly navigate and survive over 300 handcrafted levels, destroy the most epic bosses around and truly be the two-dimensional hero (or heroes!) you've always dreamed you could be.",
    "Full Metal Furies":"From the creators of Rogue Legacy comes a \"true-cooperative\" action RPG. FULL METAL FURIES puts an emphasis on team play with a unique combat system where everyone is important. Work together to defeat special enemies, string organics combos to deal massive damage, and save a wartorn world that is battling itself to extinction. Play on the couch or online with friends, and make it a party for up to four players! Or go solo in single-player, and show off your skills through a Pick 2 quick-switch system that retains all the nuances of multi-play.",
    "Gang Beasts":"Gang Beasts is a silly multiplayer party game with surly gelatinous characters, brutal slapstick fight sequences, and absurd hazardous environments, set in the mean streets of Beef City. Customise your character and fight local and online enemies in the melee game mode or fight with friends against the gangs of Beef City in the gang game mode. Gang Beasts is made by Boneloaf, a small independent game studio making a series of experimental multiplayer party games.",
    "Hammerwatch":"A hack and slash action adventure, set in a fantasy pixel art environment. Play solo or co-op in this adventure from bottom to top of Castle Hammerwatch. Kill hordes of enemies with varied looks and features through four unique environments with traps, hidden secrets and puzzles.",
    "HardLander":"Hard Lander is a tough-as-nails \"Rocket Wrestling\" arena designed for up to 4 players. Invite three of your friends to compete for bragging rights and couch cred in what might be the most advanced rocket wrestling simulation ever created! Practice your piloting expertise through 40 punishing challenge courses that will be sure to have you throwing your controller across the room as you hone your skills.",
    "Hidden in Plain Sight":"Hidden in Plain Sight is a set of local multiplayer (2-4 players) game modes that share a common theme: trying to accomplish goals without drawing attention to yourself. In each game mode, players control characters in a sea of identical NPCs. Players are given a task, but also the means to eliminate each other from the game. The goal is to blend in with the NPCs, accomplish the task at hand, and take out other players before they get you. One of the simplest game modes is called \"Death Race.\" Players and NPCs are racing to be the first to cross a finish line. Each player has a gun with one bullet, and can eliminate one person from the race. Do you sprint ahead, calling attention to yourself but maximizing you chances of winning? Or do you hang back with the pack? Other game modes create similar tension by putting players in a conflicted position of wanting to accomplish a goal, but risking elimination by doing so. Rounds are quick and lively, and always end in laughter and friendly shouting. So grab your controllers and friends and give it a shot!",
    "Human Fall Flat":"Get ready to take a hike in a brand new update for Human: Fall Flat! You'll want to wrap up tight before setting off on this trek, as the path from the hunting lodge to the mountain summit is a perilous one that passes through icy glacial caverns and a freezing fog that hides many a trap for the unwary. As you travel along this path you'll have to gingerly explore secret caves and tunnels, traverse broken bridges, grapple with hooks and ziplines, climb up trees and clamber across rocks to reach the exit at the top of the trail. Have fun!",
    "The Jackbox Party Pack 2":"The sequel to the party game phenomenon The Jackbox Party Pack, featuring FIVE fresh, rib-tickling party games! Your phones or tablets are your controllers - no big mess of controllers needed. For up to 8 players plus an Audience of up to 10,000! It's a game-night riot in a box… without the box!",
    "Killer Queen Black":"Killer Queen Black, inspired by the hit arcade game, Killer Queen, let's you fight for your hive with three ways to win. Will you claim your victory by hopping on the snail, hoarding berries, or wiping out the enemy's queen? Attack, fly, and stay alive. If you are playing queen, you'll want to protect your hive and your workers. The responsibilities don't stop there, having a strategy in place will be beneficial, but you'll also need to be fluid and keen on your opposing team's strategy. Want responsibilities but rather hustle than dodge death? Workers excel in adaptability which makes them essential for carrying out game-winning objectives. Initially defenseless, workers collect berries and head to the hive, however, they can also boost their speed and become soldiers. These transformed workers wield maces, swords, shields, and laser rifles, to quickly become deadly aggressors.",
    "Lance A Lot":"Grab your couch and your friends and get ready to lance a lot. Lance A Lot® is a fast-paced local multiplayer game about jousting. Except you're on rockets. Because let's face it, knights on rockets are way cooler. And if anyone says otherwise, then challenge them to a duel and prove them wrong!",
    "Lara Croft and the Temple of Osiris":"Lara Croft and the Temple of Osiris is the sequel to the critically-acclaimed Lara Croft and the Guardian of Light, and the first-ever four-player co-op experience with Lara Croft. Featuring stunning visuals and a brand-new story, players must work together to explore the temple, defeat hordes of enemies from the Egyptian underworld, solve devious puzzles, and avoid deadly traps. All the while, players will compete for treasure, powerful artifacts, and ultimate bragging rights. Lara Croft and the Temple of Osiris takes place deep in the deserts of Egypt. In her new adventure, Lara must join forces with rival treasure hunter Carter Bell and imprisoned gods Horus and Isis, to defeat the evil god Set. As Lara and her companions fight the elements of nature across the sands and through ancient tombs, they will battle legendary deities and creatures of myth. With the fate of the world at stake, Lara must recover the fragments of Osiris to stop Set from enslaving all mankind.",
    "Laser Lasso Ball":"Out there... somewhere is a drifting rogue-planet entirely covered by a massive crowd. The crowd waits in darkness for The BALL to spawn. When The BALL spawns, individuals are pulled into the arena, controlled by unseen entities to battle to the death in a frightening fast paced ALIEN DEATHSPORT.",
    "Lovers in a Dangerous Spacetime":"LOVERS IN A DANGEROUS SPACETIME is a frantic 1- to 4-player couch co-op action space shooter. Explore a colorful galaxy in a massive neon battleship that you control together by manning turrets, lasers, shields and thrusters. Only through teamwork can you triumph over the evil forces of Anti-Love, rescue kidnapped space-bunnies, and avoid a vacuumy demise. Deep space is a dangerous place, but you don't have to face it alone!",
    "Magicka":"Magicka is a satirical action-adventure game set in a rich fantasy world based on Norse mythology. The player assumes the role of a wizard from a sacred order tasked with stopping an evil sorcerer who has thrown the world into turmoil, his foul creations besieging the forces of good.",
    "Mimic Arena":"Mimic Arena is a local couch multiplayer platform shooter that focuses on high energy and quick reflexes. Up to four buddies are pitted against one another, but only those who have mastered the arts of jump and shoot dare hope to stand a chance, thankfully you will have some backup. Everything the player does, wherever they go, and wherever they fire; is recorded and then played back again as a Mimic. These clones will be an integrate part of any players arsenal. Providing distractions and supporting fire for new players and enabling more advanced strategy such as zoning and coordinated attacks for veterans. Throughout the battle players and Mimics alike will be able to equip themselves with an assortment of weapons such as the reflective disk that travels like a boomerang and reflects projectiles or the Phase Beam that instantly pierces through terrain and all attempting to use it as cover. With the right weapon and these clones can prove to be a dependable ally or a troublesome enemy. Control your shots for precision and efficiency or let them fly wild and embrace the bullet storm that is bound to ensue, just be sure to watch your back.",
    "Move or Die":"Move or Die is the frenzied and unpredictable 4-player party game where the rules change every 20 seconds. With only ONE constant: If you don't move, you DIE. Whether on the couch with friends or playing online with people from around the world, join the mayhem at any given time and put a bit of BOOM in your everyday life",
    "Nidhogg":"Nidhogg is the epic award-winning fencing tug-of-war, full of graceful acrobatics and clumsy stabs. IRL yelling and excitement may occur, in this ultimate two-player showdown of fast-paced fencing and melee attacks. Beware, advantages in Nidhogg are often fleeting, as new opponents continually spawn in your way. Use a variety of fencing maneuvers while armed -- lunges, parries, and even dirty tricks like throwing your sword. If swordless, press forward with punches, sweep kicks, dive kicks, rolls, and wall jumps. The combat arena stretches in both directions, although besting an opponent only gains you ground. Matches aren't won or lost with a single kill, but with a series of kills granting you right-of-way to run/fight/flee to your own goal-zone. Each arena holds different strategic formations and chokepoints to use to your advantage. Until you reach your goal-zone, anything is possible. Only one thing is certain in Nidhogg… the only way to win is to outwit your opponent. En Garde!",
    "No Heroes Here":"When evil looms close and devastation is certain… Who will have what it takes to save the day? NO HEROES HERE is a hectic co-op game for one to four players. Coordination and cooperation are your key weapons to success - everyone must play a role in the battles to come and work together as a team in order to protect the castles and Kingdom from imminent doom. Forces beyond your understanding have struck with terror and chaos. The King's broken army and fallen heroes cannot protect you from harm. It is up to you to protect the realm from evil and restore Noobland to glory!",
    "Overcooked":"Overcooked is a chaotic couch co-op cooking game for one to four players. Working as a team, you and your fellow chefs must prepare, cook and serve up a variety of tasty orders before the baying customers storm out in a huff. Sharpen your knives and dust off your chef's whites, there isn't mushroom for error and the steaks are high in these crazy kitchens!",
    "PICO PARK":"PICO PARK:Classic Edition is a cooperative local multiplay action puzzle game for 2-10 players.",
    "Pummel Party":"Pummel Party is a 4-8 player online and local-multiplayer party game. Pummel friends or AI using a wide array of absurd items in the board mode and compete to destroy friendships in the entertaining collection of minigames.",
    "Risk of Rain":"Risk of Rain is an action platformer with roguelike elements. With permanent death as a primary feature, players will have to play their best to get as far as possible. Fight on a mysterious planet with randomly spawning enemies and bosses, either alone or with 3 friends in online co-op. With over 100 items at your disposal, you will find the tools you need to find the teleporter back home. Discover a myriad of randomly chosen stages, from the desolate forest to the frozen tundra.",
    "Rocket League":"Rocket League is a high-powered hybrid of arcade-style soccer and vehicular mayhem with easy-to-understand controls and fluid, physics-driven competition. Rocket League includes casual and competitive Online Matches, a fully-featured offline Season Mode, special “Mutators” that let you change the rules entirely, hockey and basketball-inspired Extra Modes, and more than 500 trillion possible cosmetic customization combinations.",
    "ROCKETSROCKETSROCKETS":"ROCKETS fire ROCKETS at ROCKETS in this action-arcade, arena-combat, gorgeous festival-of-fireworks! It's dogfighting meets figure-skating in space with local multiplayer and single-player fast-paced action modes plus a ZEN MODE where ROCKETS learn to LOVE.",
    "ROUNDS":"Rounds is a 1v1 rogue-lite shooter where each round gets more intense. The losing player of each round unlocks clever upgrades to create a better build to counter their opponent.",
    "Screencheat":"Screencheat is a ridiculous competitive split-screen first-person shooter where everyone is invisible, so players are forced to look at each other's screens to win. Supporting both local and online multiplayer, combat in Screencheat is fast and furious with a wide variety of one-hit kill weapons.",
    "STARWHAL":"The local multi-player space narwhal fighting game that has rocked the internet is finally ready for its big debut in a fully loaded release! Flop it out with 1-4 players in a retro, epic narwhal battle in space! The heart-piercing action is furious and unrelenting. STARWHAL will change your life.",
    "Stick Fight":"Stick Fight is a physics-based couch/online fighting game where you battle it out as the iconic stick figures from the golden age of the internet. Fight it out against your friends or find random sticks from around the world!",
    "Totall Reliable Delivery Service":"Welcome to Totally Reliable Open Beta! Totally Reliable is a ragdoll physics simulation about terrible package delivery couriers. Work together using odd machinery, useful gadgets, and the wonders of physics to deliver packages...or try to at least!",
    "Towerfall Ascension":"TowerFall Ascension is the definitive version of the hit archery combat game. Inspired by classics from the golden age of couch multiplayer, it's a 4-player local party game centering around hilarious, intense versus matches. The core mechanics are simple and accessible, but hard to master and combat is fierce. Loot treasure chests for game-changing power-ups, master the art of catching arrows out of the air, or descend on your foes and stomp them into submission. TowerFall is best played competitively with friends, cross-legged on the floor within punching distance of each other.",
    "Tricky Towers":"Grab your wizard's robe and spell book, time to use your engineering skills and build some Tricky Towers! Stack your bricks and use your spells to create the tallest stable tower, for what self-respecting wizard wouldn't want to show off their skills by towering literally over their peers! But be wary of jealous rivals, who will try and push your tower down with nefarious dark spells to ensure their dominance. Block these spells to protect your tower,… oh and be sure to return the favor with your own devious magics. Match your tower wizardry against 3 others in local multiplayer, or challenge wizards around the world in an online battle of magics and engineering mayhem. Try your skills in various tricky wizard trials and set a high score on the leaderboards. So be sure to bring your wizard's safety hat and start stacking and tumbling!",
    "Trine 2":"Trine 2 is a sidescrolling game of action, puzzles and platforming where you play as one of Three Heroes who make their way through dangers untold in a fantastical fairytale world. Join Amadeus the Wizard, Pontius the Knight and Zoya the Thief in their adventure full of friendship, magic and betrayal.",
    "Ultimate Chicken Horse":"Ever wish you were a wall-jumping, arrow-dodging, trap-setting horse, besting your animal pals in a race through a peril-laden obstacle course that you all built together? Wish Granted! Ultimate Chicken Horse is a party platformer where you and your friends build the level as you play, placing deadly traps before trying to reach the end of the level. If you can make it but your friends can't, you score points! Play online or locally with your animal buddies and experiment with a wide variety of platforms in all sorts of strange locations to find new ways to mess with your friends.",
    "Unrailed!":"Unrailed! is a chaotic online and couch co-op multiplayer railroad construction game where you work together with your friends as a team to build a train track across endless procedurally generated worlds. Master encounters with its inhabitants, upgrade your train and keep it from derailing!",
    "Unrailed 2: Back on Track":"Unrailed 2: Back on Track brings chaotic local and online multiplayer track-building action to the next level – band together with friends to collaborate and build your track across new procedurally generated worlds - WHILST the train is running! So think fast, with more freedom than ever before, and conquer new obstacles in your way - before your trains becomes… a trainwreck!",
    "Vampire Survivors":"Vampire Survivors is a time survival game with minimalistic gameplay and roguelite elements. Hell is empty, the devils are here, and there's no place to run or hide. All you can do is survive as long as you can until death inevitably puts an end to your struggles. Gather gold in each run to buy upgrades and help the next survivor.",
    "Wand Wars":"Wand Wars is a fast-paced, top-down, magical sports game. Players ride brooms over ancient arenas, cast arcane spells and turn opponents into adorable chickens! Try to control a powerful magical sphere that bounces around the arena, increasing in speed and size over time. The game's epic stages, colorful characters and quirky powerups generate competitive gameplay that is incredibly fun to participate in and spectate. Hone your skills and uncover the magical universe of Wand Wars in Story Mode or battle your way through the unlimited chaos of The Trials. Play against up to 3 friends or the computer in 7 exciting multiplayer modes.",
    "Worms Reloaded":"Ten years on from Worms™ Armageddon and the turn-based comic mayhem continues in Worms™ Reloaded, an all-new edition available for PC through Steam. Worms™ Reloaded features up to four player online and offline multi-player, voice support, a raft of crazy new weapons (and the return of some iconic weapons from the brand's celebrated past), achievements (*note: Mac & Linux versions have a reduced number of achievements), leaderboards, all new high-definition landscape themes, a range of brilliant forts for the new Fort mode, new landscape editor, new play modes, hats, skins and speech banks. To top it all off, there is also a highly-involving single-player experience with tutorials, deathmatches, races, fort games and puzzles. Enjoy the new High Definition full colour graphics engine, revised physics and pit your wits against the all-new A.I. with seven personality types, ranging from easy to very hard and styles like vengeful, cocky and 'Darksider'! The game is also packed with customization options, and includes thousands of possibilities for your team of worms, tons of game options and custom levels, so you can play the game how you want!"
}

if __name__ == "__main__":
    context = zmq.Context()
    socket = context.socket(zmq.REP)
    socket.bind("tcp://*:5558")
    print("Game Description Microservice waiting on port 5558...")

    while True:
        game_name = socket.recv_string()

        # find matches to the fragment
        if game_name in game_descriptions:
            print(f"Received game name: {game_name}")
            socket.send_string(game_descriptions[game_name])
            print(f"Responded with description for {game_name}")
        else:
            socket.send_string("")



