# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGridLayout, QGroupBox,
    QHBoxLayout, QLabel, QLineEdit, QMainWindow,
    QPlainTextEdit, QPushButton, QScrollArea, QSizePolicy,
    QSpacerItem, QStackedWidget, QVBoxLayout, QWidget)
import GameArt_rc

class Ui_w_MainWindow(object):
    def setupUi(self, w_MainWindow):
        if not w_MainWindow.objectName():
            w_MainWindow.setObjectName(u"w_MainWindow")
        w_MainWindow.resize(640, 480)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(w_MainWindow.sizePolicy().hasHeightForWidth())
        w_MainWindow.setSizePolicy(sizePolicy)
        w_MainWindow.setMinimumSize(QSize(640, 480))
        w_MainWindow.setMaximumSize(QSize(640, 480))
        w_MainWindow.setBaseSize(QSize(640, 480))
        w_MainWindow.setWindowTitle(u"Simple Game Library")
        self.centralwidget = QWidget(w_MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.pnl_pages = QStackedWidget(self.centralwidget)
        self.pnl_pages.setObjectName(u"pnl_pages")
        self.intro_page = QWidget()
        self.intro_page.setObjectName(u"intro_page")
        self.verticalLayout = QVBoxLayout(self.intro_page)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.lbl_title = QLabel(self.intro_page)
        self.lbl_title.setObjectName(u"lbl_title")
        font = QFont()
        font.setPointSize(36)
        font.setBold(True)
        self.lbl_title.setFont(font)
        self.lbl_title.setText(u"Simple Game Library")
        self.lbl_title.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout.addWidget(self.lbl_title)

        self.lbl_subtitle = QLabel(self.intro_page)
        self.lbl_subtitle.setObjectName(u"lbl_subtitle")
        font1 = QFont()
        font1.setPointSize(20)
        self.lbl_subtitle.setFont(font1)
        self.lbl_subtitle.setText(u"Keeping track of your games,\n"
"so you don't have to.")
        self.lbl_subtitle.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout.addWidget(self.lbl_subtitle)

        self.groupBox = QGroupBox(self.intro_page)
        self.groupBox.setObjectName(u"groupBox")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy1)
        font2 = QFont()
        font2.setPointSize(18)
        font2.setBold(True)
        self.groupBox.setFont(font2)
        self.groupBox.setTitle(u"Did you know...")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.verticalLayout_2 = QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(32, -1, -1, 16)
        self.lbl_tips = QLabel(self.groupBox)
        self.lbl_tips.setObjectName(u"lbl_tips")
        self.lbl_tips.setText(u"tips text")

        self.verticalLayout_2.addWidget(self.lbl_tips)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_2.addItem(self.verticalSpacer)


        self.verticalLayout.addWidget(self.groupBox)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.btn_begin = QPushButton(self.intro_page)
        self.btn_begin.setObjectName(u"btn_begin")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.btn_begin.sizePolicy().hasHeightForWidth())
        self.btn_begin.setSizePolicy(sizePolicy2)
        self.btn_begin.setMinimumSize(QSize(200, 0))
        self.btn_begin.setMaximumSize(QSize(16777215, 16777215))
        font3 = QFont()
        font3.setPointSize(20)
        font3.setBold(True)
        self.btn_begin.setFont(font3)
        self.btn_begin.setAutoFillBackground(False)
        self.btn_begin.setText(u"Begin")
        self.btn_begin.setFlat(False)

        self.horizontalLayout.addWidget(self.btn_begin)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_2)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.pnl_pages.addWidget(self.intro_page)
        self.library_page = QWidget()
        self.library_page.setObjectName(u"library_page")
        self.verticalLayout_3 = QVBoxLayout(self.library_page)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.widget = QWidget(self.library_page)
        self.widget.setObjectName(u"widget")
        self.horizontalLayout_2 = QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.btn_LibraryHome = QPushButton(self.widget)
        self.btn_LibraryHome.setObjectName(u"btn_LibraryHome")
        sizePolicy.setHeightForWidth(self.btn_LibraryHome.sizePolicy().hasHeightForWidth())
        self.btn_LibraryHome.setSizePolicy(sizePolicy)
        self.btn_LibraryHome.setMinimumSize(QSize(72, 72))
        self.btn_LibraryHome.setMaximumSize(QSize(72, 72))
        font4 = QFont()
        font4.setPointSize(14)
        font4.setBold(True)
        self.btn_LibraryHome.setFont(font4)
        self.btn_LibraryHome.setText(u"\ud83c\udfe0\n"
"Home")

        self.horizontalLayout_2.addWidget(self.btn_LibraryHome)

        self.lbl_LibraryTitle = QLabel(self.widget)
        self.lbl_LibraryTitle.setObjectName(u"lbl_LibraryTitle")
        font5 = QFont()
        font5.setPointSize(26)
        font5.setBold(True)
        self.lbl_LibraryTitle.setFont(font5)
        self.lbl_LibraryTitle.setText(u"Game Library")
        self.lbl_LibraryTitle.setScaledContents(False)
        self.lbl_LibraryTitle.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_2.addWidget(self.lbl_LibraryTitle)

        self.widget_4 = QWidget(self.widget)
        self.widget_4.setObjectName(u"widget_4")
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QSize(72, 72))
        self.widget_4.setMaximumSize(QSize(72, 72))

        self.horizontalLayout_2.addWidget(self.widget_4)


        self.verticalLayout_3.addWidget(self.widget)

        self.widget_2 = QWidget(self.library_page)
        self.widget_2.setObjectName(u"widget_2")
        self.horizontalLayout_3 = QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.btn_add_game = QPushButton(self.widget_2)
        self.btn_add_game.setObjectName(u"btn_add_game")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.btn_add_game.sizePolicy().hasHeightForWidth())
        self.btn_add_game.setSizePolicy(sizePolicy3)
        self.btn_add_game.setFont(font4)
        self.btn_add_game.setStyleSheet(u"QPushButton {\n"
"	padding: 10px;\n"
"}")
        self.btn_add_game.setText(u"\u2795 Add Game")

        self.horizontalLayout_3.addWidget(self.btn_add_game)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_3)

        self.dd_sort_by = QComboBox(self.widget_2)
        self.dd_sort_by.addItem(u"Name")
        self.dd_sort_by.addItem(u"Genre")
        self.dd_sort_by.addItem(u"Year")
        self.dd_sort_by.setObjectName(u"dd_sort_by")
        self.dd_sort_by.setFont(font4)
        self.dd_sort_by.setStyleSheet(u"QComboBox {\n"
"	padding: 10px;\n"
"}")
        self.dd_sort_by.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToContents)

        self.horizontalLayout_3.addWidget(self.dd_sort_by)


        self.verticalLayout_3.addWidget(self.widget_2)

        self.widget_3 = QWidget(self.library_page)
        self.widget_3.setObjectName(u"widget_3")
        self.verticalLayout_4 = QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.sa_games = QScrollArea(self.widget_3)
        self.sa_games.setObjectName(u"sa_games")
        self.sa_games.setWidgetResizable(True)
        self.w_game_grid = QWidget()
        self.w_game_grid.setObjectName(u"w_game_grid")
        self.w_game_grid.setGeometry(QRect(0, 0, 620, 326))
        self.grid_games = QGridLayout(self.w_game_grid)
        self.grid_games.setObjectName(u"grid_games")
        self.sa_games.setWidget(self.w_game_grid)

        self.verticalLayout_4.addWidget(self.sa_games)


        self.verticalLayout_3.addWidget(self.widget_3)

        self.pnl_pages.addWidget(self.library_page)
        self.view_page = QWidget()
        self.view_page.setObjectName(u"view_page")
        self.verticalLayout_6 = QVBoxLayout(self.view_page)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.widget_7 = QWidget(self.view_page)
        self.widget_7.setObjectName(u"widget_7")
        self.horizontalLayout_4 = QHBoxLayout(self.widget_7)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.btn_ViewHome = QPushButton(self.widget_7)
        self.btn_ViewHome.setObjectName(u"btn_ViewHome")
        self.btn_ViewHome.setMinimumSize(QSize(72, 72))
        self.btn_ViewHome.setMaximumSize(QSize(72, 72))

        self.horizontalLayout_4.addWidget(self.btn_ViewHome)

        self.lbl_ViewTitle = QLabel(self.widget_7)
        self.lbl_ViewTitle.setObjectName(u"lbl_ViewTitle")
        self.lbl_ViewTitle.setFont(font5)
        self.lbl_ViewTitle.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_4.addWidget(self.lbl_ViewTitle)

        self.widget_9 = QWidget(self.widget_7)
        self.widget_9.setObjectName(u"widget_9")
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setMinimumSize(QSize(72, 72))
        self.widget_9.setMaximumSize(QSize(72, 72))

        self.horizontalLayout_4.addWidget(self.widget_9)


        self.verticalLayout_6.addWidget(self.widget_7)

        self.widget_10 = QWidget(self.view_page)
        self.widget_10.setObjectName(u"widget_10")
        self.gridLayout_2 = QGridLayout(self.widget_10)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.scrollArea = QScrollArea(self.widget_10)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 620, 382))
        self.horizontalLayout_6 = QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.lbl_ViewDescription = QLabel(self.scrollAreaWidgetContents)
        self.lbl_ViewDescription.setObjectName(u"lbl_ViewDescription")
        self.lbl_ViewDescription.setFont(font2)

        self.horizontalLayout_6.addWidget(self.lbl_ViewDescription)

        self.lbl_ViewGameArt = QLabel(self.scrollAreaWidgetContents)
        self.lbl_ViewGameArt.setObjectName(u"lbl_ViewGameArt")
        self.lbl_ViewGameArt.setMinimumSize(QSize(200, 0))
        self.lbl_ViewGameArt.setMaximumSize(QSize(200, 16777215))
        self.lbl_ViewGameArt.setPixmap(QPixmap(u":/GameArt/placeholder.png"))
        self.lbl_ViewGameArt.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)

        self.horizontalLayout_6.addWidget(self.lbl_ViewGameArt)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)


        self.verticalLayout_6.addWidget(self.widget_10)

        self.pnl_pages.addWidget(self.view_page)
        self.add_page = QWidget()
        self.add_page.setObjectName(u"add_page")
        self.verticalLayout_5 = QVBoxLayout(self.add_page)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.widget_5 = QWidget(self.add_page)
        self.widget_5.setObjectName(u"widget_5")
        self.horizontalLayout_5 = QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.btn_AddHome = QPushButton(self.widget_5)
        self.btn_AddHome.setObjectName(u"btn_AddHome")
        sizePolicy.setHeightForWidth(self.btn_AddHome.sizePolicy().hasHeightForWidth())
        self.btn_AddHome.setSizePolicy(sizePolicy)
        self.btn_AddHome.setMinimumSize(QSize(72, 72))
        self.btn_AddHome.setMaximumSize(QSize(72, 72))
        self.btn_AddHome.setFont(font4)
        self.btn_AddHome.setText(u"\ud83c\udfe0\n"
"Home")

        self.horizontalLayout_5.addWidget(self.btn_AddHome)

        self.lbl_AddTitle = QLabel(self.widget_5)
        self.lbl_AddTitle.setObjectName(u"lbl_AddTitle")
        self.lbl_AddTitle.setFont(font5)
        self.lbl_AddTitle.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_5.addWidget(self.lbl_AddTitle)

        self.widget_6 = QWidget(self.widget_5)
        self.widget_6.setObjectName(u"widget_6")
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QSize(72, 72))
        self.widget_6.setMaximumSize(QSize(72, 72))

        self.horizontalLayout_5.addWidget(self.widget_6)


        self.verticalLayout_5.addWidget(self.widget_5)

        self.label_2 = QLabel(self.add_page)
        self.label_2.setObjectName(u"label_2")
        font6 = QFont()
        font6.setPointSize(12)
        font6.setBold(True)
        self.label_2.setFont(font6)
        self.label_2.setTextFormat(Qt.TextFormat.PlainText)
        self.label_2.setWordWrap(True)
        self.label_2.setMargin(10)

        self.verticalLayout_5.addWidget(self.label_2)

        self.widget_8 = QWidget(self.add_page)
        self.widget_8.setObjectName(u"widget_8")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy4)
        self.comboBox = QComboBox(self.widget_8)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(0, 50, 81, 34))
        self.comboBox.setFont(font4)
        self.comboBox.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.comboBox_2 = QComboBox(self.widget_8)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(131, 50, 218, 34))
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy5)
        self.comboBox_2.setFont(font4)
        self.comboBox_2.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.lineEdit = QLineEdit(self.widget_8)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(0, 0, 351, 38))
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy6)
        font7 = QFont()
        font7.setPointSize(18)
        self.lineEdit.setFont(font7)
        self.plainTextEdit = QPlainTextEdit(self.widget_8)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(0, 90, 351, 181))
        font8 = QFont()
        font8.setPointSize(14)
        self.plainTextEdit.setFont(font8)
        self.pushButton = QPushButton(self.widget_8)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(390, 230, 191, 40))
        self.pushButton.setFont(font2)
        self.pushButton_2 = QPushButton(self.widget_8)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(360, 0, 261, 38))
        self.pushButton_2.setFont(font4)
        self.label_4 = QLabel(self.widget_8)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(431, 43, 120, 180))
        self.label_4.setMinimumSize(QSize(120, 180))
        self.label_4.setMaximumSize(QSize(120, 180))
        self.label_4.setPixmap(QPixmap(u":/GameArt/placeholder.png"))
        self.label_4.setScaledContents(True)

        self.verticalLayout_5.addWidget(self.widget_8)

        self.pnl_pages.addWidget(self.add_page)

        self.gridLayout.addWidget(self.pnl_pages, 0, 0, 1, 1)

        w_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(w_MainWindow)

        self.pnl_pages.setCurrentIndex(0)
        self.btn_begin.setDefault(True)


        QMetaObject.connectSlotsByName(w_MainWindow)
    # setupUi

    def retranslateUi(self, w_MainWindow):

        self.btn_ViewHome.setText(QCoreApplication.translate("w_MainWindow", u"PushButton", None))
        self.lbl_ViewTitle.setText(QCoreApplication.translate("w_MainWindow", u"Game Name", None))
        self.lbl_ViewDescription.setText(QCoreApplication.translate("w_MainWindow", u"TextLabel", None))
        self.lbl_ViewGameArt.setText("")
        self.lbl_AddTitle.setText(QCoreApplication.translate("w_MainWindow", u"Add Game", None))
        self.label_2.setText(QCoreApplication.translate("w_MainWindow", u"Fill in all the details about the game. Either browse your files for art, or drag & drop a file onto the placeholder image. If you don't have game art saved to your computer, don't worry; a placeholder image will be used instead. When done, click the Add Game button.", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("w_MainWindow", u"1980", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("w_MainWindow", u"1981", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("w_MainWindow", u"1982", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("w_MainWindow", u"1983", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("w_MainWindow", u"1984", None))
        self.comboBox.setItemText(5, QCoreApplication.translate("w_MainWindow", u"1985", None))
        self.comboBox.setItemText(6, QCoreApplication.translate("w_MainWindow", u"1986", None))
        self.comboBox.setItemText(7, QCoreApplication.translate("w_MainWindow", u"1987", None))
        self.comboBox.setItemText(8, QCoreApplication.translate("w_MainWindow", u"1988", None))
        self.comboBox.setItemText(9, QCoreApplication.translate("w_MainWindow", u"1989", None))
        self.comboBox.setItemText(10, QCoreApplication.translate("w_MainWindow", u"1990", None))
        self.comboBox.setItemText(11, QCoreApplication.translate("w_MainWindow", u"1991", None))
        self.comboBox.setItemText(12, QCoreApplication.translate("w_MainWindow", u"1992", None))
        self.comboBox.setItemText(13, QCoreApplication.translate("w_MainWindow", u"1993", None))
        self.comboBox.setItemText(14, QCoreApplication.translate("w_MainWindow", u"1994", None))
        self.comboBox.setItemText(15, QCoreApplication.translate("w_MainWindow", u"1995", None))
        self.comboBox.setItemText(16, QCoreApplication.translate("w_MainWindow", u"1996", None))
        self.comboBox.setItemText(17, QCoreApplication.translate("w_MainWindow", u"1997", None))
        self.comboBox.setItemText(18, QCoreApplication.translate("w_MainWindow", u"1998", None))
        self.comboBox.setItemText(19, QCoreApplication.translate("w_MainWindow", u"1999", None))
        self.comboBox.setItemText(20, QCoreApplication.translate("w_MainWindow", u"2000", None))
        self.comboBox.setItemText(21, QCoreApplication.translate("w_MainWindow", u"2001", None))
        self.comboBox.setItemText(22, QCoreApplication.translate("w_MainWindow", u"2002", None))
        self.comboBox.setItemText(23, QCoreApplication.translate("w_MainWindow", u"2003", None))
        self.comboBox.setItemText(24, QCoreApplication.translate("w_MainWindow", u"2004", None))
        self.comboBox.setItemText(25, QCoreApplication.translate("w_MainWindow", u"2005", None))
        self.comboBox.setItemText(26, QCoreApplication.translate("w_MainWindow", u"2006", None))
        self.comboBox.setItemText(27, QCoreApplication.translate("w_MainWindow", u"2007", None))
        self.comboBox.setItemText(28, QCoreApplication.translate("w_MainWindow", u"2008", None))
        self.comboBox.setItemText(29, QCoreApplication.translate("w_MainWindow", u"2009", None))
        self.comboBox.setItemText(30, QCoreApplication.translate("w_MainWindow", u"2010", None))
        self.comboBox.setItemText(31, QCoreApplication.translate("w_MainWindow", u"2011", None))
        self.comboBox.setItemText(32, QCoreApplication.translate("w_MainWindow", u"2012", None))
        self.comboBox.setItemText(33, QCoreApplication.translate("w_MainWindow", u"2013", None))
        self.comboBox.setItemText(34, QCoreApplication.translate("w_MainWindow", u"2014", None))
        self.comboBox.setItemText(35, QCoreApplication.translate("w_MainWindow", u"2015", None))
        self.comboBox.setItemText(36, QCoreApplication.translate("w_MainWindow", u"2016", None))
        self.comboBox.setItemText(37, QCoreApplication.translate("w_MainWindow", u"2017", None))
        self.comboBox.setItemText(38, QCoreApplication.translate("w_MainWindow", u"2018", None))
        self.comboBox.setItemText(39, QCoreApplication.translate("w_MainWindow", u"2019", None))
        self.comboBox.setItemText(40, QCoreApplication.translate("w_MainWindow", u"2020", None))
        self.comboBox.setItemText(41, QCoreApplication.translate("w_MainWindow", u"2021", None))
        self.comboBox.setItemText(42, QCoreApplication.translate("w_MainWindow", u"2022", None))
        self.comboBox.setItemText(43, QCoreApplication.translate("w_MainWindow", u"2023", None))
        self.comboBox.setItemText(44, QCoreApplication.translate("w_MainWindow", u"2024", None))
        self.comboBox.setItemText(45, QCoreApplication.translate("w_MainWindow", u"2025", None))

        self.comboBox.setPlaceholderText(QCoreApplication.translate("w_MainWindow", u"Year", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("w_MainWindow", u"Adventure", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("w_MainWindow", u"Action", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("w_MainWindow", u"Action Adventure", None))
        self.comboBox_2.setItemText(3, QCoreApplication.translate("w_MainWindow", u"Action RPG", None))
        self.comboBox_2.setItemText(4, QCoreApplication.translate("w_MainWindow", u"Battle Royale", None))
        self.comboBox_2.setItemText(5, QCoreApplication.translate("w_MainWindow", u"Casual", None))
        self.comboBox_2.setItemText(6, QCoreApplication.translate("w_MainWindow", u"Fighting", None))
        self.comboBox_2.setItemText(7, QCoreApplication.translate("w_MainWindow", u"First-Person Shooter", None))
        self.comboBox_2.setItemText(8, QCoreApplication.translate("w_MainWindow", u"Idle", None))
        self.comboBox_2.setItemText(9, QCoreApplication.translate("w_MainWindow", u"MMORPG", None))
        self.comboBox_2.setItemText(10, QCoreApplication.translate("w_MainWindow", u"Party", None))
        self.comboBox_2.setItemText(11, QCoreApplication.translate("w_MainWindow", u"Platformer", None))
        self.comboBox_2.setItemText(12, QCoreApplication.translate("w_MainWindow", u"Puzzle", None))
        self.comboBox_2.setItemText(13, QCoreApplication.translate("w_MainWindow", u"Racing", None))
        self.comboBox_2.setItemText(14, QCoreApplication.translate("w_MainWindow", u"RPG", None))
        self.comboBox_2.setItemText(15, QCoreApplication.translate("w_MainWindow", u"Shooter", None))
        self.comboBox_2.setItemText(16, QCoreApplication.translate("w_MainWindow", u"Simulation", None))
        self.comboBox_2.setItemText(17, QCoreApplication.translate("w_MainWindow", u"Sports", None))
        self.comboBox_2.setItemText(18, QCoreApplication.translate("w_MainWindow", u"Stealth", None))
        self.comboBox_2.setItemText(19, QCoreApplication.translate("w_MainWindow", u"Strategy", None))
        self.comboBox_2.setItemText(20, QCoreApplication.translate("w_MainWindow", u"Survival", None))

        self.comboBox_2.setCurrentText("")
        self.comboBox_2.setPlaceholderText(QCoreApplication.translate("w_MainWindow", u"Genre", None))
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("w_MainWindow", u"Game Name", None))
        self.plainTextEdit.setPlaceholderText(QCoreApplication.translate("w_MainWindow", u"Game Description", None))
        self.pushButton.setText(QCoreApplication.translate("w_MainWindow", u"\u2795 Add Game", None))
        self.pushButton_2.setText(QCoreApplication.translate("w_MainWindow", u"Browse for game art... \ud83d\udcc2", None))
        self.label_4.setText("")
        pass
    # retranslateUi

